### ISSUE TITLE
Cédulas nuevas 

### ISSUE THREAD

**Issue by aloysiusan** [alexvargasbenamburg/android_LectorCedulas#1]
Vi este proyecto bastante interesante así que me puse a probarlo pero veo que no soporta las cédulas nuevas, debería poder leerlas o hay que hacer algún cambio en las llaves del algoritmo?

**Comment by vbalexr** [comment]
Hola,
Pues no he echo ningún cambio al algoritmo y si puedo leer los datos de las cédulas nuevas, el no te reconoce la cedula o no te da los resultados correctos? Que versión de android estas usando?

**Comment by aloysiusan** [comment]
No da los datos correctos, sale basura, y lo probe con Android 5.1.1

**Comment by vbalexr** [comment]
Voy a hacer pruebas, que versión de sdk usaste para compilar o solo descargaste y compilaste?

**Comment by aloysiusan** [comment]
Solo lo descargué y compilé y funcionó excelente con las cédulas viejas pero las nuevas no logré que sirviera

**Comment by vbalexr** [comment]
Acabo de realizar pruebas y si me funciona! podes enviarme una foto del CODIGO de la cédula que te da errores?

**Comment by aloysiusan** [comment]
Si claro a cuál correo?

**Comment by vbalexr** [comment]
Al que uso acá: vb.alexr@gmail.com

**Comment by vbalexr** [comment]
Estoy cambiando mi cédula para poder hacer mas pruebas en efecto parece que algo cambio, te mantengo al tanto!

**Comment by alexvargasbenamburg** [comment]
Estoy cambiando mi cédula para poder hacer mas pruebas en efecto parece que algo cambio, te mantengo al tanto!

**Comment by ghost** [comment]
Hola, si se ocupa una cédula nueva que comience con el dígito 8 puedo pasarle foto para tener más muestras. 👍

**Comment by vbalexr** [comment]
@fdelapena Seria de mucha ayuda! Enviamela a mi correo!

**Comment by ghost** [comment]
Enviada 👍. ¡Éxitos!

**Comment by CodingAleCR** [comment]
¿Será que la llave de encriptación cambió? Muy buen repo.

**Comment by vbalexr** [comment]
No creo, por que eso haría que todos los lectores actuales dejaran de leer.

**Comment by aloysiusan** [comment]
Yo contacté al TSE, y dijeron que en efecto la llevé cambio, intenté solicitar la nueva pero ellos lo que dan es un DLL ya con el algoritmo compilado, o sea "tome y úselo en su programa de windows", supongo que funciona muy bien para lectores actuales que por detrás usan windows para obtener los datos. Consulté que yo lo necesitaba para una app móvil, pero me dijeron que eso era lo único que daban.

**Comment by jlberrocal** [comment]
y pasando ese dll por algo como [esto](https://social.msdn.microsoft.com/Forums/vstudio/en-US/05b3cf5d-ead3-4274-88f5-6e8cbda8e8d8/decompiling-a-dll-file-to-view-source-code?forum=msbuild)??

o bien podrías compartirlo y ver si alguien puede leer el nuevo key

**Comment by aloysiusan** [comment]
es una buena idea, apenas tenga el DLL a mano, lo probaré

**Comment by CodingAleCR** [comment]
Al final si lo pediste? A mi me solicitaron cartas, firmas y demás :/

**Comment by aloysiusan** [comment]
Si, la empresa me está ayudando con todo ese papeleo

**Comment by vbalexr** [comment]
@aloysiusan excelente, estaré atento y disponible para colaborar.

**Comment by aloysiusan** [comment]
UPDATE: en teoría entre mañana y lunes me envían el archivo del TSE (me dieron la opción del DLL o uno para linux, pedí el de linux por que creo que mas sencillo). Sin embargo, desde que vi este proyecto he estado intentando portarlo a iOS ya que es para esa plataforma que yo lo necesito, hasta hoy no había podido hacer que funcionara por la forma en la que iOS devuelve los datos leídos. Hoy logré implementarlo usando este port de [zxing](https://github.com/TheLevelUp/ZXingObjC), y lo curioso fue que SÍ esta funcionando con las cédulas nuevas, usando la misma llave de antes. Por lo que me queda la duda de por qué en android estaba fallando. De cualquier forma aquí les dejo la versión de [iOS](https://github.com/aloysiusan/LectorCedulaCR) por si desean verla. Yo la probé con varias cédulas nuevas y esta funcionando

**Comment by ghost** [comment]
No sé si https://github.com/alexvargasbenamburg/android_LectorCedulas/issues/2#issuecomment-338082669 podría ser un motivo de por qué falla al parsear.

**Comment by kendall1997** [comment]
Buenas tardes,

he estado al pendiente de este tema y he hecho la migración de Java a Javascript del código encargado de decodificar y parsear la información de la cédula, ya que me interesa implementarlo en móvil con Ionic.

El código sería el siguiente:

```javascript
#!/usr/bin/node

const raw = []; //Acá va los datos de la cédula, proveniente del escáner.
const key = [0x27,0x30,0x04,0xA0,0x00,0x0F,0x93,0x12,0xA0,0xD1,0x33,0xE0,0x03,0xD0,0x00,0xDf,0x00];

const build = input => {
  return {
    id : (input.substring(0, 9).trim()),
    lastname : (input.substring(9, 35).trim()),
    lastname2 : (input.substring(35, 61).trim()),
    name : (input.substring(61, 91).trim()),
    gender : (input.charAt(91)),
    birthday : (input.substring(92, 96)+"-"+input.substring(96, 98)+"-"+input.substring(98, 100)),
    expiration : (input.substring(100, 104)+"-"+input.substring(104, 106)+"-"+input.substring(106, 108))
  };
}

const decrypt = (raw,key) => {
  let pattern = new RegExp("^[a-zA-Z0-9]*$");
  let output = '';
  let subindex = 0;
  for (let index = 0; index < raw.length; ++index) {
    if (subindex == 17) {
        subindex = 0;
    }
    let char = (key[subindex] ^ ((raw[index])));
    if(pattern.test(String.fromCharCode(char)+"")){
        output += String.fromCharCode(char);
    }else{
        output += ' ';
    }
    ++subindex;
  }
  return output;
};

const source = decrypt(raw,key);
const human = build(source);
console.log(human);
```

Les comento la prueba que he realizado:

1. Obtener la información de la cédula (App: https://play.google.com/store/apps/details?id=mobi.pdf417&hl=es_419) y utilizar su representación como arreglo de bytes (no convertirlo a String, ya que se generan caracteres no visibles, para evitar conflictos).
2. Utilizar el flujo de bytes del paso 1 y establecerlo en la constante raw del código anterior.
3. Ejecutarlo en la terminal.

El resultado de la prueba anterior me indica correctamente los datos de las cédulas, tanto nuevas como viejas. Por lo que considero que la llave no cambió.

Pienso que puede ser un conflicto con los paquetes 'com.journeyapps.barcodescanner.CaptureManager' y 'com.journeyapps.barcodescanner.DecoratedBarcodeView' a la hora de decodificar la imagen.

**Comment by aloysiusan** [comment]
Entonces el problema no es el código, sino la biblioteca utilizada en android para obtener los datos de la cedula

**Comment by vbalexr** [comment]
Hola,
Acabo de crear un branch alternativo usando una biblioteca privativa de microblink, es para probar con la cédulas nuevas, podrían  ayudarme con las pruebas? 
Aca esta el branch: https://github.com/alexvargasbenamburg/android_LectorCedulas/tree/alternative
Dejo los compilados aca: https://github.com/alexvargasbenamburg/android_LectorCedulas/releases/tag/v0.1a

**Comment by ghost** [comment]
@alexvargasbenamburg he probado el APK debug y consigue decodificar información con el PDF417 de la cédula nueva, por lo que la llave no parece haber cambiado.
Aparece número de cédula, apellidos y nombre (la eñe falla, muestra un espacio), fecha de nacimiento y de vencimiento.

He intentado instalar los dos pares de APK, solo puedo instalar el 0.1a debug. Para los otros 3 me dice Android: "Aplicación no instalada", si ocupas información de logcat me avisas.

**Comment by lmorar00** [comment]
>           Yo contacté al TSE, y dijeron que en efecto la llevé cambio, intenté solicitar la nueva pero ellos lo que dan es un DLL ya con el algoritmo compilado, o sea "tome y úselo en su programa de windows", supongo que funciona muy bien para lectores actuales que por detrás usan windows para obtener los datos. Consulté que yo lo necesitaba para una app móvil, pero me dijeron que eso era lo único que daban.

Buenas Lograron conseguir la DLL?

Saludos.

**Comment by vbalexr** [comment]
Revisado, la clave no ha cambiado, pueden verificar con el código del repositorio [alternativo](https://github.com/cedulacr/lector_Android/tree/alternative), funciona con cedulas viejas y nuevas. El problema es con la biblioteca de lectura PDF417
