### ISSUE TITLE
Implementado en Desktop

### ISSUE THREAD

**Issue by ghost** [alexvargasbenamburg/android_LectorCedulas#2]
El descifrado se puede implementar en una aplicacion desktop(Java) utilizado lector de codigo.?

**Comment by vbalexr** [comment]
Si, aún no lo he echo pero se que si puede, el proyecto está basado en
https://github.com/zxing/zxing he visto proyectos que lo usan en desktop!
Por ahora estoy viendo cómo hago para que funcione con las cédulas nuevas!

**Comment by ghost** [comment]
Gracias por tu aporte. Felicitaciones por tu proyecto.

**Comment by vbalexr** [comment]
Pensándolo un poco, si gustas podríamos hacer un branch para ir trabajando en esta versión. Y gracias :D

**Comment by ghost** [comment]
Se ve interesante en la clase CedulaCR esa son las llaves del TSE.

**Comment by vbalexr** [comment]
Si ves el README, ahí esta la llave y el algoritmo por separado!

**Comment by B-Carcamo** [comment]
Hice pruebas con la cedula nueva en una aplicacion Desktop pero no me la descifro adapte tu codigo para el descifrado.

      Persona p;
      String datos = TextDatos1.getText() // JtextArea donde se registra la lectura de codigo de barra pdf417
       byte[]byteArray = new byte[datos.length()];            
        for(int i =0 ;i<byteArray.length;i++){
            byteArray[i]=(byte)datos.codePointAt(i);
        }
        
      p = CedulaCR.parse(byteArray);

**Comment by vbalexr** [comment]
Aca implementación para un RPI, funciona tambien para pc, solo cambiar la libreria de dynamsoft.
https://github.com/cedulacr/lector_RPi
