### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by demogar** [alexvargasbenamburg/android_LectorCedulas#4]
Amigo, saludos desde Panamá. Tengo algunas preguntas acerca de la implementación, ya que creo que compartimos (Panamá y Costa Rica) alguna similitud en la implementación.

¿Cómo supiste el tipo de cifrado que se utilizo, en este caso de tipo XOR?
¿Cómo supiste la llave para descifrar? ¿te la entregaron o tuviste que hacer ingeniería inversa?

Mil gracias amigo.

**Comment by CodingAleCR** [comment]
En Costa Rica, dependiendo de la utilidad, se le pueden entregar la clave para realizar la lib.

**Comment by vbalexr** [comment]
Hola, realmente fue un poco de "suerte" estaba haciendo un proyecto X donde usaba PDF417 y vi que era lo que usaba la cédula, lo demás fue solo un poco de "trabajo duro"
