### ISSUE TITLE
APK compilado?

### ISSUE THREAD

**Issue by schweini** [alexvargasbenamburg/android_LectorCedulas#5]
Hola!
Usted tiene un apk ya compilado, para probar esto?

**Comment by CodingAleCR** [comment]
Lo que puede hacer es clonar el repo o hacerle un fork y correrlo con Android Studio o IntelliJ Idea, o el ambiente de desarrollo para Android que prefiera.

**Comment by vbalexr** [comment]
Acabo de hacer un build y lo agrege como release.
https://github.com/alexvargasbenamburg/android_LectorCedulas/releases/tag/v0.1

**Comment by schweini** [comment]
Gracias!

Lo traté de instalar, y al final solo dice "app not installed".

Me extraña un poco que al inicio me decía que "this app doesn't require any
special permissions".

Android 8.1.0 (LineageOS 15.1 en un OneplusOne bacon)

**Comment by vbalexr** [comment]
Prueba con la version firmada! https://github.com/alexvargasbenamburg/android_LectorCedulas/releases/download/v0.1/lector_dni_cr_signed.apk

**Comment by schweini** [comment]
Gracias! El firmado si me funcionó.

Pero solamente con cédulas viejas - la nueva no logro leer, aún que la
amplíe en la computadora y todo.

Usted sabe si la nueva lleva el código de barras en el mismo formato que la
vieja?

Gracias!

**Comment by vbalexr** [comment]
Si es el mismo, doy por cerrado este hilo puedes seguir este: #1
