### ISSUE TITLE
Lectura de codigo de barras de cedula

### ISSUE THREAD

**Issue by lmorar00** [alexvargasbenamburg/android_LectorCedulas#7]
Buenas,

Queria saber si me pueden guiar con este tema, necesito hacer un programa de escritorio que me lea la informacion de la cedulas nuevas y viejas.

Saludos.

**Comment by vbalexr** [comment]
Para ello, ocupas algun lector del código, puedes usar [zxing](https://github.com/zxing/zxing) y luego lo decodificas con el codigo en [esta clase](https://github.com/cedulacr/lector_Android/blob/master/Lector/src/main/java/com/vbalex/cedulascr/CedulaCR.java)

**Comment by lmorar00** [comment]
Hola Alex,

Muchas Gracias por tu respuesta.

Estuve viendo el código en GitHub.

Hay una clase que se llama CedulaCR, las cual tiene una función que se llama parse, que me imagino que es la que descodifica el arreglo de bytes que le paso a esa función y la función parse me devuelve un tipo de dato persona que esta basada en la clase Persona.

Es asi cómo funciona?

Saludos.

**Comment by vbalexr** [comment]
Correcto.

**Comment by lmorar00** [comment]
Hola Alex

Espero que este bien.

Yo aqui molestando. Me prestaron un scanner para scanner la cedula y me devolvió este resultado.



0—4?§"—’{¡U•Sß'0
________________________________
 “ Ñ3à
________________________________
Ðß'cMìE\“ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ~¡V‚O AkuNáNKÁ] Ñ3à
________________________________
Ðß'0
________________________________

Þ#™èÑ2à3í05‘19“ Ñ3à
________________________________
Ð1é[1]:0Fü O)¢l¸™ªŒ‘¤d39HŠ¤w«óf²ªq¬nva’,m¬ó€ÑlC“uª|®~°²
¢'~sóf$MFld“*ípë­×|ŽYÑ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “
Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________

“ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'2/ >Vl’ ´¨lP²·u¡lS?g¿zˆJ›Qws^›@“`â¥ ‹%
èµO‰úˆi© §5œc
                 †½§RL¸ª—•Ž  •:\¬x§u¬œfV¦KÐUt÷wÐ{{ÈºŸú: °‹^_ zn Ñ3à
________________________________
Ðß'0
________________________________
 “
 Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________
 “ Ñ3à
________________________________
Ðß'0
________________________________

Como hago para almacenar esto en una variable para pasárselo al método parse.

Trate declarar una variable, pero la encierro entre comillas dobles y me genera un error

[cid:image002.png@01D4D167.5F953E40]

Gracias por la ayuda que me puedas brindar

Saludos.

**Comment by vbalexr** [comment]
Esto no tiene que ver diractamente con la biblioteca, pero te comento, eso que pegaste es la reprensentacion ACII de los bytes leidos, para poderlos trabajar debes de imprimir los valores decimales o aplicar 'escape' a cada caracter, y meterlos dentro de un array en el codigo.

**Comment by lmorar00** [comment]
Hola Alex,

Gracias por responder.

Esta clase principal donde estoy probando lo que se escaneo con el scanner

[cid:image001.png@01D4D27E.D0FF94F0]

Lo que esta en la variable datos, es lo que supuestamente leyó el scanner, luego lo paso por el for y aplico la función parse.

Pero me esta generando eso como resultado. No sé si estoy tratando mal la data que se escaneo.

[cid:image002.png@01D4D27F.4FA63840]

**Comment by vbalexr** [comment]
No se ven las imagenes.

**Comment by lmorar00** [comment]
Hola Alex,

Disculpa.

Te adjunto las imagenes

Saludos.
